import type { AgentInfo, FailureHeatmapStage, Run } from './types'

export const mockAgents: AgentInfo[] = [
  {
    id: 'agent-shopping',
    name: 'Shopping Cart Calculator',
    role: 'Food & Grocery Order Calculator',
    category: 'shopping',
    avatarColor: 'lime',
    description: 'Calculates item subtotals, applies promo discount codes, adds delivery fees, and validates receipt balances.',
    model: 'GPT-4.1 mini',
    totalRuns: 245,
    successRate: 88.5,
    avgDuration: '1.24s',
    failureCount: 28,
    topFailureStage: 'Apply Discount Coupon',
    status: 'degraded',
    recentTask: 'Order: 2 Pizzas ($15 each) + 1 Soda ($4) with 20% coupon & $5 delivery',
  },
  {
    id: 'agent-tipsplit',
    name: 'Dinner Bill & Tip Splitter',
    role: 'Restaurant Bill & Equal Splitter',
    category: 'math',
    avatarColor: 'cyan',
    description: 'Calculates percentage tips for restaurant checks and splits the final balance evenly among friends.',
    model: 'GPT-4.1 mini',
    totalRuns: 310,
    successRate: 91.2,
    avgDuration: '0.98s',
    failureCount: 27,
    topFailureStage: 'Equal Division per Person',
    status: 'healthy',
    recentTask: 'Split $100 dinner bill among 4 friends with 15% tip',
  },
  {
    id: 'agent-temp',
    name: 'Temperature Converter',
    role: 'Fahrenheit to Celsius Converter',
    category: 'converter',
    avatarColor: 'orange',
    description: 'Converts temperature scales accurately using standard thermodynamic formulas.',
    model: 'GPT-4.1 mini',
    totalRuns: 195,
    successRate: 89.7,
    avgDuration: '0.82s',
    failureCount: 20,
    topFailureStage: 'Conversion Formula Execution',
    status: 'healthy',
    recentTask: 'Convert human body temperature 98.6°F to Celsius',
  },
  {
    id: 'agent-grades',
    name: 'Student Grade Evaluator',
    role: 'Exam Score Average & GPA Assigner',
    category: 'grades',
    avatarColor: 'violet',
    description: 'Calculates average percentage from exam scores and assigns letter grades (A, B, C, F).',
    model: 'Claude 3.7 Sonnet',
    totalRuns: 180,
    successRate: 93.3,
    avgDuration: '1.10s',
    failureCount: 12,
    topFailureStage: 'Score Sum & Average',
    status: 'healthy',
    recentTask: 'Calculate average of test scores [85, 90, 95] for final grade',
  },
]

export const mockHeatmapStages: FailureHeatmapStage[] = [
  {
    stageId: 'stage-parse',
    stageName: '1. Parse Items & Quantities',
    failureCount: 4,
    percentage: 4.6,
    avgAnomalyScore: 22,
    trend: 'stable',
    trendChange: '0.0%',
    commonErrors: ['Unrecognized coupon code format', 'Missing unit quantity in request'],
  },
  {
    stageId: 'stage-subtotal',
    stageName: '2. Compute Item Subtotals',
    failureCount: 8,
    percentage: 9.2,
    avgAnomalyScore: 35,
    trend: 'down',
    trendChange: '-1.5%',
    commonErrors: ['Negative quantity parsed', 'Missing item price in catalog'],
  },
  {
    stageId: 'stage-discount',
    stageName: '3. Apply Percentage Discount / Tip',
    failureCount: 48,
    percentage: 55.2,
    avgAnomalyScore: 92,
    trend: 'up',
    trendChange: '+8.4%',
    commonErrors: [
      'Multiplied whole percentage instead of fraction (e.g., 34 * 20 = $680 instead of $6.80)',
      'Discount exceeded order subtotal',
      'Negative bill balance emitted',
    ],
  },
  {
    stageId: 'stage-delivery',
    stageName: '4. Add Delivery / Split Per Person',
    failureCount: 18,
    percentage: 20.7,
    avgAnomalyScore: 68,
    trend: 'down',
    trendChange: '-2.1%',
    commonErrors: ['Halted due to negative upstream subtotal', 'Division by zero on party size'],
  },
  {
    stageId: 'stage-receipt',
    stageName: '5. Output Receipt & Final Answer',
    failureCount: 9,
    percentage: 10.3,
    avgAnomalyScore: 45,
    trend: 'stable',
    trendChange: '+0.2%',
    commonErrors: ['Blocked by safety guardrail on illegal total', 'Rounding error on cents'],
  },
]

export const mockHeatmapMatrix = [
  { agentName: 'Shopping Cart Calculator', parse: 2, subtotal: 3, discount: 28, delivery: 8, receipt: 5, total: 46 },
  { agentName: 'Dinner Bill & Tip Splitter', parse: 1, subtotal: 2, discount: 12, delivery: 7, receipt: 2, total: 24 },
  { agentName: 'Temperature Converter', parse: 1, subtotal: 1, discount: 6, delivery: 2, receipt: 1, total: 11 },
  { agentName: 'Student Grade Evaluator', parse: 0, subtotal: 2, discount: 2, delivery: 1, receipt: 1, total: 6 },
]

export const mockRuns: Run[] = [
  {
    id: 'RUN-101',
    task: 'Order: 2 Pizzas ($15 each) + 1 Soda ($4) with 20% coupon & $5 delivery',
    agentId: 'agent-shopping',
    agentName: 'Shopping Cart Calculator',
    status: 'failed',
    failureCategory: 'calculation',
    duration: '1.42s',
    durationMs: 1420,
    tokens: '420',
    tokenCount: 420,
    time: 'Just now',
    date: 'Oct 03, 19:45:00',
    model: 'GPT-4.1 mini',
    traceId: 'trc_pizza_cart_101',
    hasCheckpoint: true,
    checkpointStep: 3,
    replayOutputPreset: 'Discount applied: $6.80 (20% of $34.00) | Discounted Subtotal: $27.20',
    failureDiagnosis: {
      confidence: 99,
      suspectedStepNumber: 3,
      suspectedStepTitle: 'Apply 20% Discount Coupon',
      failureCategory: 'calculation',
      categoryLabel: 'Calculation Formula Error',
      rootCause:
        'The agent calculated 20% of $34 by multiplying 34 * 20 = $680.00 instead of 34 * 0.20 = $6.80. This plunged the customer balance into -$646.00, causing downstream steps to halt and trip guardrails.',
      evidence: [
        'Step 3 produced discount of $680.00, which is 20x larger than the entire $34.00 subtotal.',
        'Downstream Step 4 (Delivery Fee) refused to process a negative balance of -$646.00.',
        'Guardrail violation: Customer final charge cannot be negative.',
      ],
      recommendedFix:
        'Update Step 3 formula to multiply subtotal by 0.20 ($34 * 0.20 = $6.80). The correct discounted subtotal is $27.20.',
      suggestedPatch: 'Discount applied: $6.80 (20% of $34.00) | Discounted Subtotal: $27.20',
      analyzedBy: 'Black Box AI Formula Verifier',
    },
    steps: [
      {
        id: 'step-101-1',
        stepNumber: 1,
        title: 'Parse Order Items & Quantities',
        status: 'success',
        duration: '0.25s',
        durationMs: 250,
        tokens: 85,
        tool: 'order_parser',
        input: 'Order: 2 Pizzas @ $15.00 each, 1 Soda Drink @ $4.00, Promo: "SAVE20", Delivery: $5.00',
        output: JSON.stringify(
          {
            items: [
              { name: 'Pizza', quantity: 2, unitPrice: 15.0, itemTotal: 30.0 },
              { name: 'Soda Drink', quantity: 1, unitPrice: 4.0, itemTotal: 4.0 },
            ],
            couponCode: 'SAVE20',
            discountPercentage: 20,
            deliveryFee: 5.0,
          },
          null,
          2
        ),
      },
      {
        id: 'step-101-2',
        stepNumber: 2,
        title: 'Compute Base Subtotal',
        status: 'success',
        duration: '0.18s',
        durationMs: 180,
        tokens: 65,
        tool: 'math_subtotal',
        input: 'Items: 2x Pizza ($30.00) + 1x Soda ($4.00)',
        output: 'Subtotal = $30.00 + $4.00 = $34.00',
      },
      {
        id: 'step-101-3',
        stepNumber: 3,
        title: 'Apply 20% Discount Coupon',
        status: 'failed',
        duration: '0.45s',
        durationMs: 450,
        tokens: 120,
        tool: 'discount_calculator',
        input: 'Subtotal: $34.00, Coupon: "SAVE20" (20% OFF)',
        output: 'Discount = 34 * 20 = $680.00\nNew Subtotal = 34.00 - 680.00 = -$646.00',
        warning: 'CRITICAL BUG: Multiplied by 20 instead of 0.20! Discount exceeds order subtotal.',
        errorDetail: 'AssertionError: Negative subtotal -$646.00 is illegal. Process halted.',
        anomalyScore: 98,
      },
      {
        id: 'step-101-4',
        stepNumber: 4,
        title: 'Add Delivery Fee ($5.00)',
        status: 'suspicious',
        duration: '0.00s',
        durationMs: 0,
        tokens: 0,
        tool: 'delivery_tool',
        input: 'Subtotal: -$646.00, Delivery Fee: +$5.00',
        output: '[PROCESS HALTED] Step skipped due to fatal calculation defect at Step 3.',
        warning: 'Execution blocked by upstream failure.',
      },
      {
        id: 'step-101-5',
        stepNumber: 5,
        title: 'Generate Final Customer Receipt',
        status: 'failed',
        duration: '0.00s',
        durationMs: 0,
        tokens: 0,
        tool: 'receipt_generator',
        input: 'Compile and format final customer invoice',
        output: '[BLOCKED] Refusing to charge customer with negative balance.',
        errorDetail: 'Process aborted before customer credit card charge was made.',
      },
    ],
  },
  {
    id: 'RUN-102',
    task: 'Split $100 dinner bill among 4 friends with 15% tip',
    agentId: 'agent-tipsplit',
    agentName: 'Dinner Bill & Tip Splitter',
    status: 'failed',
    failureCategory: 'calculation',
    duration: '1.18s',
    durationMs: 1180,
    tokens: '380',
    tokenCount: 380,
    time: '4 min ago',
    date: 'Oct 03, 19:41:10',
    model: 'GPT-4.1 mini',
    traceId: 'trc_dinner_tip_102',
    hasCheckpoint: true,
    checkpointStep: 4,
    replayOutputPreset: 'Total with 15% Tip: $115.00 | Split among 4 friends: $28.75 per person',
    failureDiagnosis: {
      confidence: 96,
      suspectedStepNumber: 4,
      suspectedStepTitle: 'Split Total Among 4 People',
      failureCategory: 'calculation',
      categoryLabel: 'Missing Tip in Division',
      rootCause:
        'The agent calculated the 15% tip ($15.00) in Step 2, but in Step 4 it divided the original $100 instead of the $115 total. Each person was charged $25.00, leaving a $15.00 unpaid tip deficit.',
      evidence: [
        'Total collected: 4 friends x $25.00 = $100.00, but restaurant check was $115.00.',
        'Waitstaff tip shortfall: $15.00 missing from final collection.',
      ],
      recommendedFix: 'Divide the grand total ($115.00) by 4 friends: $115.00 / 4 = $28.75 per person.',
      suggestedPatch: 'Split among 4 friends: $115.00 / 4 = $28.75 per person',
      analyzedBy: 'Black Box AI Formula Verifier',
    },
    steps: [
      {
        id: 'step-102-1',
        stepNumber: 1,
        title: 'Parse Dinner Bill & Party Size',
        status: 'success',
        duration: '0.20s',
        durationMs: 200,
        tokens: 60,
        tool: 'bill_parser',
        input: 'Bill: $100.00, Party Size: 4 people, Tip: 15%',
        output: 'Parsed: checkAmount = $100.00, guests = 4, tipPercent = 15%',
      },
      {
        id: 'step-102-2',
        stepNumber: 2,
        title: 'Calculate 15% Tip Amount',
        status: 'success',
        duration: '0.15s',
        durationMs: 150,
        tokens: 50,
        tool: 'calculator',
        input: '$100.00 * 0.15',
        output: 'Tip Amount = $15.00',
      },
      {
        id: 'step-102-3',
        stepNumber: 3,
        title: 'Compute Grand Total',
        status: 'success',
        duration: '0.12s',
        durationMs: 120,
        tokens: 45,
        tool: 'calculator',
        input: '$100.00 + $15.00',
        output: 'Grand Total with Tip = $115.00',
      },
      {
        id: 'step-102-4',
        stepNumber: 4,
        title: 'Split Total Among 4 People',
        status: 'failed',
        duration: '0.35s',
        durationMs: 350,
        tokens: 95,
        tool: 'division_tool',
        input: 'Compute per-person share',
        output: 'Divided original $100 / 4 = $25.00 per person (Forgot to include $15 tip!)',
        warning: 'Deficit detected: Collected $100.00, but required amount is $115.00!',
        errorDetail: 'ShortfallError: Under-collected $15.00.',
      },
      {
        id: 'step-102-5',
        stepNumber: 5,
        title: 'Emit Payment Summary',
        status: 'failed',
        duration: '0.00s',
        durationMs: 0,
        tokens: 0,
        tool: 'summary_tool',
        input: 'Emit payment breakdown',
        output: '[BLOCKED] Total payments do not match restaurant invoice.',
        errorDetail: 'Bill reconciliation failed.',
      },
    ],
  },
  {
    id: 'RUN-103',
    task: 'Convert human body temperature 98.6°F to Celsius',
    agentId: 'agent-temp',
    agentName: 'Temperature Converter',
    status: 'failed',
    failureCategory: 'calculation',
    duration: '0.94s',
    durationMs: 940,
    tokens: '290',
    tokenCount: 290,
    time: '12 min ago',
    date: 'Oct 03, 19:33:15',
    model: 'GPT-4.1 mini',
    traceId: 'trc_temp_conv_103',
    hasCheckpoint: true,
    checkpointStep: 2,
    replayOutputPreset: 'Formula: (98.6 - 32) * 5/9 = 37.0°C (Normal Human Body Temperature)',
    failureDiagnosis: {
      confidence: 98,
      suspectedStepNumber: 2,
      suspectedStepTitle: 'Apply Temperature Conversion Formula',
      failureCategory: 'calculation',
      categoryLabel: 'Inverted Formula Error',
      rootCause:
        'The agent used the Celsius-to-Fahrenheit formula instead of Fahrenheit-to-Celsius: (98.6 * 9/5) + 32 = 209.48°C. A body temperature of 209°C is biologically impossible and tripped medical safety guards.',
      evidence: [
        'Calculated 209.48°C, which exceeds the boiling point of water (100°C).',
        'Standard medical range: 35.0°C to 42.0°C.',
        'Guardrail: Impossible physiological temperature.',
      ],
      recommendedFix: 'Use Fahrenheit-to-Celsius formula: (F - 32) * 5/9 = (98.6 - 32) * 5/9 = 37.0°C.',
      suggestedPatch: 'Formula: (98.6 - 32) * 5/9 = 37.0°C (Normal Human Body Temperature)',
      analyzedBy: 'Black Box AI Formula Verifier',
    },
    steps: [
      {
        id: 'step-103-1',
        stepNumber: 1,
        title: 'Read Temperature & Source Scale',
        status: 'success',
        duration: '0.15s',
        durationMs: 150,
        tokens: 45,
        tool: 'input_parser',
        input: 'Input: 98.6 degrees Fahrenheit, Target: Celsius',
        output: 'Parsed: value = 98.6, source = "Fahrenheit", target = "Celsius"',
      },
      {
        id: 'step-103-2',
        stepNumber: 2,
        title: 'Apply Temperature Conversion Formula',
        status: 'failed',
        duration: '0.40s',
        durationMs: 400,
        tokens: 110,
        tool: 'math_formula',
        input: 'Apply conversion to 98.6',
        output: 'Formula used: (98.6 * 9/5) + 32 = 209.48°C',
        warning: 'Medical Guardrail: 209.48°C exceeds boiling point of water! Lethal value.',
        errorDetail: 'FormulaInversionError: Used C->F formula instead of F->C.',
      },
      {
        id: 'step-103-3',
        stepNumber: 3,
        title: 'Validate Physiological Safety & Return',
        status: 'failed',
        duration: '0.00s',
        durationMs: 0,
        tokens: 0,
        tool: 'guardrail_tool',
        input: 'Check 209.48°C against medical bounds',
        output: '[BLOCKED] Value 209.48°C rejected by safety filter.',
        errorDetail: 'Guardrail rejected output.',
      },
    ],
  },
  {
    id: 'RUN-104',
    task: 'Calculate average of test scores [85, 90, 95] for final grade',
    agentId: 'agent-grades',
    agentName: 'Student Grade Evaluator',
    status: 'failed',
    failureCategory: 'calculation',
    duration: '1.05s',
    durationMs: 1050,
    tokens: '310',
    tokenCount: 310,
    time: '25 min ago',
    date: 'Oct 03, 19:20:00',
    model: 'Claude 3.7 Sonnet',
    traceId: 'trc_grades_avg_104',
    hasCheckpoint: true,
    checkpointStep: 3,
    replayOutputPreset: 'Sum: 270 / 3 exams = 90.0% | Final Grade: A (PASSED)',
    failureDiagnosis: {
      confidence: 97,
      suspectedStepNumber: 3,
      suspectedStepTitle: 'Divide Sum by Exam Count',
      failureCategory: 'calculation',
      categoryLabel: 'Divisor Count Error',
      rootCause:
        'The agent summed the 3 scores correctly (85 + 90 + 95 = 270), but divided by 4 instead of 3. This produced an erroneous average of 67.5% and incorrectly assigned a failing grade "D" to an honor-roll student.',
      evidence: [
        'Scores count is 3, but divisor used was 4.',
        'Calculated average was 67.5% instead of true average 90.0%.',
        'Student grade incorrectly marked as D (Fail) instead of A (Honors Pass).',
      ],
      recommendedFix: 'Divide 270 by 3: 270 / 3 = 90.0% (Grade A).',
      suggestedPatch: 'Sum: 270 / 3 exams = 90.0% | Final Grade: A (PASSED)',
      analyzedBy: 'Black Box AI Formula Verifier',
    },
    steps: [
      {
        id: 'step-104-1',
        stepNumber: 1,
        title: 'Parse Exam Scores Array',
        status: 'success',
        duration: '0.18s',
        durationMs: 180,
        tokens: 50,
        tool: 'array_parser',
        input: 'Scores: [85, 90, 95]',
        output: 'Parsed 3 exam scores: [85, 90, 95], count = 3',
      },
      {
        id: 'step-104-2',
        stepNumber: 2,
        title: 'Compute Sum of Scores',
        status: 'success',
        duration: '0.12s',
        durationMs: 120,
        tokens: 40,
        tool: 'sum_tool',
        input: '85 + 90 + 95',
        output: 'Total score sum = 270',
      },
      {
        id: 'step-104-3',
        stepNumber: 3,
        title: 'Divide Sum by Exam Count',
        status: 'failed',
        duration: '0.38s',
        durationMs: 380,
        tokens: 90,
        tool: 'average_calculator',
        input: 'Sum: 270, divisor: 4 (BUG!)',
        output: 'Average = 270 / 4 = 67.5%',
        warning: 'Divisor mismatch: 3 scores provided, but divided by 4!',
        errorDetail: 'MathError: Divisor count does not match input length.',
      },
      {
        id: 'step-104-4',
        stepNumber: 4,
        title: 'Assign Letter Grade & Status',
        status: 'failed',
        duration: '0.10s',
        durationMs: 100,
        tokens: 40,
        tool: 'grade_assigner',
        input: 'Score: 67.5%',
        output: 'Assigned Grade: D (FAILED) | Student marked for remedial course',
        errorDetail: 'False failure generated from calculation bug.',
      },
    ],
  },
  {
    id: 'RUN-105',
    task: 'Order 3 Burgers ($10 each) + $2 Fries with 10% coupon',
    agentId: 'agent-shopping',
    agentName: 'Shopping Cart Calculator',
    status: 'success',
    failureCategory: 'none',
    duration: '0.92s',
    durationMs: 920,
    tokens: '290',
    tokenCount: 290,
    time: '35 min ago',
    date: 'Oct 03, 19:10:00',
    model: 'GPT-4.1 mini',
    traceId: 'trc_burger_105',
    steps: [
      {
        id: 'step-105-1',
        stepNumber: 1,
        title: 'Parse Order Items',
        status: 'success',
        duration: '0.20s',
        durationMs: 200,
        tokens: 60,
        tool: 'order_parser',
        input: '3 Burgers @ $10.00, 1 Fries @ $2.00, Coupon: 10%',
        output: '3x Burger ($30.00) + 1x Fries ($2.00) | Subtotal: $32.00',
      },
      {
        id: 'step-105-2',
        stepNumber: 2,
        title: 'Apply 10% Coupon',
        status: 'success',
        duration: '0.15s',
        durationMs: 150,
        tokens: 45,
        tool: 'discount_calculator',
        input: '$32.00 * 0.10',
        output: 'Discount = -$3.20 | Subtotal after discount = $28.80',
      },
      {
        id: 'step-105-3',
        stepNumber: 3,
        title: 'Generate Receipt',
        status: 'success',
        duration: '0.12s',
        durationMs: 120,
        tokens: 50,
        tool: 'receipt_generator',
        input: 'Format total $28.80',
        output: 'Order confirmed! Total charged: $28.80 ✓',
      },
    ],
  },
  {
    id: 'RUN-106',
    task: 'Split $60 lunch among 3 people with 20% tip',
    agentId: 'agent-tipsplit',
    agentName: 'Dinner Bill & Tip Splitter',
    status: 'success',
    failureCategory: 'none',
    duration: '0.84s',
    durationMs: 840,
    tokens: '260',
    tokenCount: 260,
    time: '45 min ago',
    date: 'Oct 03, 19:00:00',
    model: 'GPT-4.1 mini',
    traceId: 'trc_lunch_106',
    steps: [
      {
        id: 'step-106-1',
        stepNumber: 1,
        title: 'Parse Lunch Bill',
        status: 'success',
        duration: '0.16s',
        durationMs: 160,
        tokens: 50,
        tool: 'bill_parser',
        input: 'Bill: $60.00, Tip: 20%, Colleagues: 3',
        output: 'Bill: $60.00, Tip: $12.00, Total: $72.00',
      },
      {
        id: 'step-106-2',
        stepNumber: 2,
        title: 'Split by 3 People',
        status: 'success',
        duration: '0.14s',
        durationMs: 140,
        tokens: 40,
        tool: 'calculator',
        input: '$72.00 / 3',
        output: 'Each person pays: $24.00 ✓',
      },
    ],
  },
  {
    id: 'RUN-107',
    task: 'Convert water freezing point 32°F to Celsius',
    agentId: 'agent-temp',
    agentName: 'Temperature Converter',
    status: 'success',
    failureCategory: 'none',
    duration: '0.78s',
    durationMs: 780,
    tokens: '210',
    tokenCount: 210,
    time: '1 hour ago',
    date: 'Oct 03, 18:45:00',
    model: 'GPT-4.1 mini',
    traceId: 'trc_temp_107',
    steps: [
      {
        id: 'step-107-1',
        stepNumber: 1,
        title: 'Read 32°F',
        status: 'success',
        duration: '0.12s',
        durationMs: 120,
        tokens: 35,
        tool: 'input_parser',
        input: '32 degrees Fahrenheit',
        output: 'Parsed: 32.0°F',
      },
      {
        id: 'step-107-2',
        stepNumber: 2,
        title: 'Compute Celsius',
        status: 'success',
        duration: '0.15s',
        durationMs: 150,
        tokens: 45,
        tool: 'math_formula',
        input: '(32 - 32) * 5/9',
        output: 'Result: 0.0°C (Water Freezing Point) ✓',
      },
    ],
  },
  {
    id: 'RUN-108',
    task: 'Average scores [70, 80, 90] for grade',
    agentId: 'agent-grades',
    agentName: 'Student Grade Evaluator',
    status: 'success',
    failureCategory: 'none',
    duration: '0.88s',
    durationMs: 880,
    tokens: '240',
    tokenCount: 240,
    time: '1 hour ago',
    date: 'Oct 03, 18:30:00',
    model: 'Claude 3.7 Sonnet',
    traceId: 'trc_grades_108',
    steps: [
      {
        id: 'step-108-1',
        stepNumber: 1,
        title: 'Sum & Average',
        status: 'success',
        duration: '0.18s',
        durationMs: 180,
        tokens: 50,
        tool: 'calculator',
        input: 'Sum: 70 + 80 + 90 = 240 / 3',
        output: 'Average: 80.0% | Assigned Grade: B (Passed) ✓',
      },
    ],
  },
  {
    id: 'RUN-109',
    task: 'Order 1 Laptop Sleeve ($25) + Mouse ($15) with free shipping',
    agentId: 'agent-shopping',
    agentName: 'Shopping Cart Calculator',
    status: 'success',
    failureCategory: 'none',
    duration: '0.85s',
    durationMs: 850,
    tokens: '230',
    tokenCount: 230,
    time: '2 hours ago',
    date: 'Oct 03, 17:40:00',
    model: 'GPT-4.1 mini',
    traceId: 'trc_sleeve_109',
    steps: [
      {
        id: 'step-109-1',
        stepNumber: 1,
        title: 'Calculate Order',
        status: 'success',
        duration: '0.22s',
        durationMs: 220,
        tokens: 60,
        tool: 'calculator',
        input: '$25.00 + $15.00 + $0.00 shipping',
        output: 'Total: $40.00 | Paid via Card ✓',
      },
    ],
  },
  {
    id: 'RUN-110',
    task: 'Split $200 hotel room between 2 guests with 10% tax',
    agentId: 'agent-tipsplit',
    agentName: 'Dinner Bill & Tip Splitter',
    status: 'success',
    failureCategory: 'none',
    duration: '0.90s',
    durationMs: 900,
    tokens: '250',
    tokenCount: 250,
    time: '3 hours ago',
    date: 'Oct 03, 16:30:00',
    model: 'GPT-4.1 mini',
    traceId: 'trc_hotel_110',
    steps: [
      {
        id: 'step-110-1',
        stepNumber: 1,
        title: 'Calculate Hotel Total',
        status: 'success',
        duration: '0.19s',
        durationMs: 190,
        tokens: 55,
        tool: 'calculator',
        input: '$200.00 + 10% tax = $220.00 / 2 guests',
        output: 'Each guest pays: $110.00 ✓',
      },
    ],
  },
  {
    id: 'RUN-111',
    task: 'Convert water boiling point 212°F to Celsius',
    agentId: 'agent-temp',
    agentName: 'Temperature Converter',
    status: 'success',
    failureCategory: 'none',
    duration: '0.75s',
    durationMs: 750,
    tokens: '190',
    tokenCount: 190,
    time: '4 hours ago',
    date: 'Oct 03, 15:20:00',
    model: 'GPT-4.1 mini',
    traceId: 'trc_boil_111',
    steps: [
      {
        id: 'step-111-1',
        stepNumber: 1,
        title: 'Convert 212°F',
        status: 'success',
        duration: '0.16s',
        durationMs: 160,
        tokens: 40,
        tool: 'calculator',
        input: '(212 - 32) * 5/9',
        output: 'Result: 100.0°C (Water Boiling Point) ✓',
      },
    ],
  },
  {
    id: 'RUN-112',
    task: 'Order 4 Coffees ($5 each) with 50% discount voucher',
    agentId: 'agent-shopping',
    agentName: 'Shopping Cart Calculator',
    status: 'suspicious',
    failureCategory: 'calculation',
    duration: '1.20s',
    durationMs: 1200,
    tokens: '320',
    tokenCount: 320,
    time: '5 hours ago',
    date: 'Oct 03, 14:15:00',
    model: 'GPT-4.1 mini',
    traceId: 'trc_coffee_112',
    hasCheckpoint: true,
    checkpointStep: 2,
    replayOutputPreset: 'Voucher verified: 50% discount applied. Subtotal: $10.00.',
    failureDiagnosis: {
      confidence: 78,
      suspectedStepNumber: 2,
      suspectedStepTitle: 'Voucher Threshold Check',
      failureCategory: 'calculation',
      categoryLabel: 'High Discount Rate Anomaly',
      rootCause:
        'A 50% discount voucher was applied without requiring supervisor authorization override. Subtotal dropped from $20.00 to $10.00.',
      evidence: ['Discount exceeded standard store limit of 30%.', 'Flagged for manager sign-off.'],
      recommendedFix: 'Require supervisor pin or confirm promotional campaign is active.',
      suggestedPatch: 'Voucher verified: 50% discount applied. Subtotal: $10.00.',
      analyzedBy: 'Black Box Store Policy Inspector',
    },
    steps: [
      {
        id: 'step-112-1',
        stepNumber: 1,
        title: 'Calculate 4 Coffees',
        status: 'success',
        duration: '0.22s',
        durationMs: 220,
        tokens: 60,
        tool: 'calculator',
        input: '4 Coffees @ $5.00',
        output: 'Subtotal: $20.00',
      },
      {
        id: 'step-112-2',
        stepNumber: 2,
        title: 'Voucher Threshold Check',
        status: 'suspicious',
        duration: '0.35s',
        durationMs: 350,
        tokens: 90,
        tool: 'policy_check',
        input: 'Apply 50% coupon',
        output: 'Applied -$10.00 discount | Balance: $10.00',
        warning: 'High discount rate (>30%) flagged for review.',
        anomalyScore: 72,
      },
      {
        id: 'step-112-3',
        stepNumber: 3,
        title: 'Emit Final Coffee Receipt',
        status: 'success',
        duration: '0.15s',
        durationMs: 150,
        tokens: 45,
        tool: 'receipt_generator',
        input: 'Final total: $10.00',
        output: 'Receipt issued with promo note: $10.00 ✓',
      },
    ],
  },
]

export const mockReplayRun = {
  originalRunId: 'RUN-101',
  replayRunId: 'RPL-101-CORRECTED',
  task: 'Order: 2 Pizzas ($15 each) + 1 Soda ($4) with 20% coupon & $5 delivery',
  agentName: 'Shopping Cart Calculator',
  model: 'GPT-4.1 mini (Replayed with Fixed Formula)',
  originalDuration: '1.42s',
  replayDuration: '0.85s',
  originalTokens: '420',
  replayTokens: '310',
  patchedStepIndex: 2,
  changedStepsCount: 3,
  timeSaved: '0.57s faster',
  tokenDelta: '-110 tokens (-26.2%)',
  reconciliationStatus: 'Verified Correct: $32.20 Total ✓',
  originalSteps: mockRuns[0].steps,
  replaySteps: [
    mockRuns[0].steps[0],
    mockRuns[0].steps[1],
    {
      id: 'step-rpl-101-3',
      stepNumber: 3,
      title: 'Apply 20% Discount Coupon (Patched)',
      status: 'success' as const,
      duration: '0.18s',
      durationMs: 180,
      tokens: 65,
      tool: 'discount_calculator',
      input: 'Subtotal: $34.00, Coupon: "SAVE20" (Formula: 34 * 0.20)',
      output: 'Discount applied: $6.80 (20% of $34.00) | Discounted Subtotal: $27.20 ✓',
      diffChanged: true,
      originalOutput: mockRuns[0].steps[2].output,
    },
    {
      id: 'step-rpl-101-4',
      stepNumber: 4,
      title: 'Add Delivery Fee ($5.00)',
      status: 'success' as const,
      duration: '0.12s',
      durationMs: 120,
      tokens: 40,
      tool: 'delivery_tool',
      input: 'Discounted Subtotal: $27.20 + Standard Delivery Fee: $5.00',
      output: 'Delivery added: $5.00 | Total with Delivery: $32.20 ✓',
      diffChanged: true,
      originalOutput: mockRuns[0].steps[3].output,
    },
    {
      id: 'step-rpl-101-5',
      stepNumber: 5,
      title: 'Generate Final Customer Receipt',
      status: 'success' as const,
      duration: '0.14s',
      durationMs: 140,
      tokens: 45,
      tool: 'receipt_generator',
      input: 'Format customer order receipt',
      output:
        'CUSTOMER RECEIPT:\n2x Pizza ($15.00): $30.00\n1x Soda ($4.00): $4.00\nSubtotal: $34.00\nDiscount (20% Coupon): -$6.80\nDelivery Fee: +$5.00\n--------------------------------\nFINAL TOTAL CHARGED: $32.20 ✓ (Order Confirmed)',
      diffChanged: true,
      originalOutput: mockRuns[0].steps[4].output,
    },
  ],
}
